Feat/more
teamGrowing/growing-web pull request #29
Opened 2023-03-01 13:43 UTC by metamoong

**📌 More Page 기능 구현**

- 프로필 사진을 앱 내 갤러리에서 선택하면 바로 선택창이 꺼지고 TopBar의 완료를 눌러야 완전히 반영이 되도록 함. 요 사이에 사진 크게보기(?) 미리보기 같은게 있으면 좋을 것 같아용
- bottomSheet에 onClick 추가
- + 이것저것 리팩토링..

2023-03-02 10:12 UTC, yeonju0110 commented on src/hooks/queries/couple.queries.ts
> +      store.userStore.getUserData(store.userStore.user?.id!);
저도 이게 고민스러운데 store를 component외의 파일에서 불러와도 괜찮을까요?.? 
사용하는 곳에서 observer를 빼먹을 수도 있지 않나 하는 생각...? 저만의 생각이에요..

2023-03-02 10:12 UTC, yeonju0110 commented on src/pages/more/ProfilePage.tsx
> +          {onCompleteModal && (
생각해보니 {onCompleteModal && ()}은 필요없습니다
Modal에 onModal로 전달해준 값이 false면 null로 반환되어서 modal이 dom tree에 올라가지않습니다!

2023-03-02 10:18 UTC, metamoong commented on src/hooks/queries/couple.queries.ts
> +      store.userStore.getUserData(store.userStore.user?.id!);
![image](https://user-images.githubusercontent.com/73338341/222399677-08c0a8b0-bd3b-4b3a-bf6e-a493e8e094dc.png)
안그래두 이부분 개발자모드에 이런게 떠서 해결하려고 draft로 바꿨습니다! action으로 하라는데 그래도 observer를 빼먹을 수도 있을 것 같긴하네요🫠🫠

2023-03-02 10:44 UTC, yeonju0110 commented on src/stores/UserStore.ts
> +import { action, makeAutoObservable } from 'mobx';
mobx action사용하라고 warning뜨는건 고쳐놨습니다!!

2023-03-03 03:37 UTC, metamoong commented on src/stores/UserStore.ts
> +import { action, makeAutoObservable } from 'mobx';
감사합니다!

2023-03-03 05:49 UTC, yeonju0110 approved these changes
PR하셔도 될 것 같아요! 다른 건 회의시간에 얘기해보아요 😆

2023-03-03 08:12 UTC, metamoong commented
> PR하셔도 될 것 같아요! 다른 건 회의시간에 얘기해보아요 😆
고치고 싶은 게 있어서 몇가지 수정했습니다!
- 프로필 수정 -> 사진 수정 -> 라이브러리에서 사진 선택 시 폼 제출 하지 않으면 photo에 업로드 되지 않도록 수정
- navbar도 min-width 설정

2023-03-05 11:32 UTC, metamoong commented
@yeonju0110 
기본 프로필 추가, 웹에서 스크롤바 안보이게 수정했습니당.
스크롤바 숨기는 건 제가 자꾸 써서 GlobalStyle에 추가했어용

2023-03-05 12:01 UTC, yeonju0110 requested changes
제가..몇 가지 이슈를 발견했습니당 🥹
### 프로필 사진 업로드
- 라이브러리에서 선택하기를 했을 때, 프로필 사진이 변경되지 않고 갤러리에만 사진이 올라가는 것 같습니다!
- 라이브러리에서 선택하기를 해서 프로필 사진 업로드시, 동영상이나 움짤 등 다른 파일형식을 선택하지 못하도록 해야할 것 같습니다!
- 갤러리에서 프로필 사진을 삭제하면 프로필 사진이 같이 사라지는 일이 발생합니다 ㅠㅡㅠ

### 갤러리
- 동영상 업로드가 잘 되지 않는 것 같아요..!

2023-03-06 08:56 UTC, metamoong commented
> 제가..몇 가지 이슈를 발견했습니당 🥹
> 
> ### 프로필 사진 업로드
> * 라이브러리에서 선택하기를 했을 때, 프로필 사진이 변경되지 않고 갤러리에만 사진이 올라가는 것 같습니다!
> * 라이브러리에서 선택하기를 해서 프로필 사진 업로드시, 동영상이나 움짤 등 다른 파일형식을 선택하지 못하도록 해야할 것 같습니다!
> * 갤러리에서 프로필 사진을 삭제하면 프로필 사진이 같이 사라지는 일이 발생합니다 ㅠㅡㅠ
> 
> ### 갤러리
> * 동영상 업로드가 잘 되지 않는 것 같아요..!

첫번째, 두번째는 해결했습니다!😭😭 
아직 앱 내 갤러리에서 프로필 선택 시 동영상도 선택이 되고, 동영상이 업로드 되면 보이지 않는데 요거는 파일이 동영상인지 사진인지 알아내야 할 것 같은데 알 수 있는 방법을 찾아보겠습니당!

세번째는 혹시 언제 그렇게 되나요..? photoPage에서 삭제 시 프로필이 사라지는 건가용..?

2023-03-06 19:52 UTC, yeonju0110 reviewed
3번째 문제는 다시 확인해보니 제가 착각했었네요..! ㅠㅠ

프로필 수정을 눌러서 이미지 변경없이 수정을 하면 기존의 프로필이미지가 아닌, null로 들어가지는 것 같습니다! 이미지 삭제를 눌르지 않아도 삭제되네용

2023-03-07 00:59 UTC, metamoong commented
> 해결된 사항 확인했습니다! 3번째 문제는 다시 확인해보니 제가 착각했었네요..! ㅠㅠ
> 
> 프로필 수정을 눌러서 이미지 변경없이 수정을 하면 기존의 프로필이미지가 아닌, null로 들어가지는 것 같습니다! 이미지 삭제를 눌르지 않아도 삭제되네용..!

옹 그러네요 수정했습니다!!

2023-03-08 12:47 UTC, yeonju0110 approved these changes
확인했습니다! 잘 작동하네요 😁

2023-03-12 15:44 UTC, metamoong commented
@yeonju0110  백엔드 수정된 거 맞춰서 video 해결했습니당!

2023-03-12 19:03 UTC, yeonju0110 approved these changes
ㅠㅠ 수고하셨습니다!!

2023-03-13 01:19 UTC, merged