Feat/calendar
teamGrowing/growing-web pull request #34
Opened 2023-03-31 08:34 UTC by metamoong

**🌈 기능사항**
- full calendar 사용하여 캘린더 재구현

**📌 참고사항**
- 새로운 패키지 추가
- 시간과 알림 기능은 추후 추가 예정

2023-03-31 12:12 UTC, yeonju0110 requested changes
넘 수고하셨습니다!! ㅠㅠ 캘린더 너무 이뻐요..👍🏻✨ 구현 넘 잘 된 것 같아요!! 💙

UI 관련해서 질문이 있습니다!
- 일정 부분을 클릭하면, 해당 날짜가 클릭되지 않습니다. 아래 코드를 추가해주시면 작동할 것 같습니다! 더 좋은 코드가 있다면, 말씀해주세용 ㅎㅎ
`
  .fc-daygrid-event-harness {
    pointer-events: none;
  }
`
- 2022년 10월처럼 달력이 6주로 긴 경우에는 TODO가 잘 보이지 않습니다! 스크롤이 가능하도록 하면 좋을 것 같습니당:)

2023-03-31 12:12 UTC, yeonju0110 commented on src/hooks/queries/calendar.queries.ts
default options이 suspense: true인데, 달이 넘어갈 때마다 깜빡이는 건 사용자 관점에서 좋지 않은 것 같습니다! 캘린더 정보를 GET해올 때는, suspense: false로 하는건 어떨까요? 🤔

2023-03-31 12:12 UTC, yeonju0110 commented on src/components/pages/calendar/TodoArea.tsx
> +  const [onBottomSheet, setOnBottomSheet] = useState(false);
사소하지만.. 뭔가 타입을 집어넣고 싶은 느낌..?입니다 😜

2023-03-31 12:12 UTC, yeonju0110 commented on src/components/pages/calendar/CalendarBottomSheet.tsx
> +        setOpen(false);
요게 반복되니까 clearInputData() 이런식으로 함수를 만들어서 써도 직관적이고 좋을 것 같아요! 🤔

2023-04-04 12:34 UTC, metamoong commented
> 넘 수고하셨습니다!! ㅠㅠ 캘린더 너무 이뻐요..👍🏻✨ 구현 넘 잘 된 것 같아요!! 💙
> 
> UI 관련해서 질문이 있습니다!
> 
> * 일정 부분을 클릭하면, 해당 날짜가 클릭되지 않습니다. 아래 코드를 추가해주시면 작동할 것 같습니다! 더 좋은 코드가 있다면, 말씀해주세용 ㅎㅎ
>   `.fc-daygrid-event-harness { pointer-events: none; }`
> * 2022년 10월처럼 달력이 6주로 긴 경우에는 TODO가 잘 보이지 않습니다! 스크롤이 가능하도록 하면 좋을 것 같습니당:)

일정이 드래그앤 드롭으로 날짜 수정이 가능하도록 되어 있어서 저거는 안될 것 같습니다ㅠㅠ 제가 일정 클릭시 날짜가 클릭되도록 할 수 있는 방법을 좀 더 고민해보고 수정하거나 드래그앤 드롭 기능을 없에거나 하겠습니다😢😢 

다른 건 다 좋은 것 같습니당👍🏻👍🏻
그리고 스크롤 가능하도록 했는데 앱에서 잘 되는 지 확인 한번만 부탁드려도 될까용ㅎㅎ❣️

2023-04-06 15:42 UTC, yeonju0110 approved these changes
헉 드래그앤 드롭 기능 넘 좋습니다! 저도 한 번 더 생각해볼게요ㅠㅠ
스크롤 너무 잘됩니다 🤍 PR 하시면 될 것 같습니다! 수고하셨습니다 ㅎㅎㅎ

2023-04-07 04:30 UTC, merged